// Code generated by "stringer -type=AppMessageType"; DO NOT EDIT.

package henv

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HENV_MSG_TYPE_REGISTER_PREFIX_HANDLER-16777216]
	_ = x[HENV_MSG_TYPE_UNREGISTER_PREFIX_HANDLER-16777217]
	_ = x[HENV_MSG_TYPE_REGISTER_LAUNCH_LISTENER-16777218]
	_ = x[HENV_MSG_TYPE_UNREGISTER_LAUNCH_LISTENER-16777219]
	_ = x[HENV_MSG_TYPE_APP_LAUNCHED-16777220]
	_ = x[HENV_MSG_TYPE_KILL-16777221]
	_ = x[HENV_MSG_TYPE_GET_PAYLOAD_NUMBER-16777222]
}

const _AppMessageType_name = "HENV_MSG_TYPE_REGISTER_PREFIX_HANDLERHENV_MSG_TYPE_UNREGISTER_PREFIX_HANDLERHENV_MSG_TYPE_REGISTER_LAUNCH_LISTENERHENV_MSG_TYPE_UNREGISTER_LAUNCH_LISTENERHENV_MSG_TYPE_APP_LAUNCHEDHENV_MSG_TYPE_KILLHENV_MSG_TYPE_GET_PAYLOAD_NUMBER"

var _AppMessageType_index = [...]uint8{0, 37, 76, 114, 154, 180, 198, 230}

func (i AppMessageType) String() string {
	i -= 16777216
	if i >= AppMessageType(len(_AppMessageType_index)-1) {
		return "AppMessageType(" + strconv.FormatInt(int64(i+16777216), 10) + ")"
	}
	return _AppMessageType_name[_AppMessageType_index[i]:_AppMessageType_index[i+1]]
}
