__asm__(
	".intel_syntax noprefix\n"
	".section .data\n"
	".global daemon_start\n"
	".type   daemon_start, @object\n"
	".align  16\n"
	"daemon_start:\n"
    	".incbin \"daemon/daemon.elf\"\n"
	"daemon_end:\n"
	    ".global daemon_size\n"
	    ".type   daemon_size, @object\n"
	    ".align  4\n"
	"daemon_size:\n"
    	".int    daemon_end - daemon_start\n"
	".global util_start\n"
	".type   util_start, @object\n"
	".align  16\n"
	"util_start:\n"
    	".incbin \"bin/util.elf\"\n"
	"util_end:\n"
	    ".global util_size\n"
	    ".type   util_size, @object\n"
	    ".align  4\n"
	"util_size:\n"
    	".int    util_end - util_start\n"
);
